# Generated by Django 4.2.5 on 2023-10-05 19:16

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=1, max_length=500, upload_to=blog.models.blog_thumbnail_directory),
            preserve_default=False,
        ),
    ]
