# Generated by Django 4.2.5 on 2023-10-26 14:34

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('postobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
